version: '3.8'

services:
  message-hub-server:
    build: .
    container_name: message-hub-server-light
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data:/app/data  # Mount for SQLite database persistence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - message-hub-network

networks:
  message-hub-network:
    driver: bridge

volumes:
  data:
    driver: local